######################################################################
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# http에서 https로 리다이렉트하 도록 구성하기
# helm install traefik traefik/traefik --values values.yaml
######################################################################
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    # Port Redirections
    # Added in 2.2, you can make permanent redirects via entrypoints
    redirectTo: websecure

######################################################################
# 참고: https://doc.traefik.io/traefik/https/acme/#httpchallenge
# https://doc.traefik.io/traefik/https/acme/
# ---
# 인증서 공급자
######################################################################

certResolvers:
   letsencrypt:
     # for challenge options cf. https://doc.traefik.io/traefik/https/acme/
     email: example@example.com
     #tlsChallenge: true
     httpChallenge:
       entryPoint: "web"
     # It has to match the path with a persistent volume
     storage: /data/acme.json
